dataset_name: QH9Dynamic
split: geometry  #[geometry, mol]

train_batch_size: 32
valid_batch_size: 32
test_batch_size: 32

learning_rate: 5e-4
validation_interval: 10
use_gradient_clipping: true
clip_norm: 5.0
pin_memory: True
num_workers: 8

warmup_steps: 1000
total_steps: 300000
lr_end: 1e-7

train_batch_interval: 100
validation_batch_interval: 1000
