name: potnet
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py37h540881e_1004
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.12.7=ha878542_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.0=py37h036bc23_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - cryptography=37.0.2=py37h38fbfac_0
  - cudatoolkit=11.6.0=hecad31d_10
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h0708190_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - idna=3.4=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h166bdaf_1
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.17=h166bdaf_0
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.2.0=hf544144_3
  - libwebp-base=1.2.2=h7f98852_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h402132d_0
  - mkl_fft=1.3.1=py37h3e078e5_1
  - mkl_random=1.2.2=py37h219a48f_0
  - ncurses=6.3=h5eee18b_3
  - nettle=3.6=he412f7d_0
  - numpy-base=1.21.5=py37ha15fc14_3
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1s=h7f8727e_0
  - pip=22.3.1=py37h06a4308_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_1
  - pysocks=1.7.1=py37h89c1867_5
  - python=3.7.15=h7a1cb2a_1
  - python_abi=3.7=2_cp37m
  - pytorch=1.12.1=py3.7_cuda11.6_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=pyhd8ed1ab_1
  - setuptools=65.5.0=py37h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.40.0=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.12.1=py37_cu116
  - torchvision=0.13.1=py37_cu116
  - typing_extensions=4.4.0=pyha770c72_0
  - urllib3=1.26.13=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.8=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - alembic==1.9.0
    - ase==3.22.1
    - attrs==22.2.0
    - autopage==0.5.1
    - blessed==1.19.1
    - bottle==0.12.25
    - click==8.1.3
    - cliff==3.10.1
    - cmaes==0.9.1
    - cmd2==2.4.2
    - colorama==0.4.6
    - colorlog==6.7.0
    - cycler==0.11.0
    - cython==0.29.33
    - dgl==0.9.1
    - dill==0.3.6
    - e3nn==0.5.1
    - fonttools==4.38.0
    - future==0.18.2
    - ghp-import==2.1.0
    - gpustat==1.0.0
    - greenlet==2.0.1
    - importlib-metadata==4.13.0
    - importlib-resources==5.10.1
    - jarvis-leaderboard==2023.5.13
    - jarvis-tools==2022.9.16
    - jinja2==3.1.2
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - llvmlite==0.39.1
    - mako==1.2.4
    - markdown==3.2.1
    - markupsafe==2.1.1
    - matplotlib==3.5.3
    - mendeleev==0.12.1
    - mergedeep==1.3.4
    - mkdocs==1.4.3
    - mkdocs-material==9.1.14
    - mkdocs-material-extensions==1.1.1
    - monty==2022.9.9
    - mpmath==1.2.1
    - networkx==2.6.3
    - numba==0.56.4
    - numpy==1.21.6
    - nvidia-ml-py==11.495.46
    - opt-einsum==3.3.0
    - opt-einsum-fx==0.1.4
    - optuna==3.2.0
    - optuna-dashboard==0.9.2
    - packaging==22.0
    - palettable==3.3.0
    - pandarallel==1.6.3
    - pandas==1.3.5
    - pbr==5.11.0
    - periodictable==1.6.1
    - pillow==9.3.0
    - plotly==5.11.0
    - prettytable==3.5.0
    - psutil==5.9.4
    - psycopg2-binary==2.9.5
    - pydantic==1.10.2
    - pyfiglet==0.8.post1
    - pygments==2.15.1
    - pymatgen==2021.3.3
    - pymdown-extensions==10.0.1
    - pyparsing==3.0.9
    - pyperclip==1.8.2
    - python-dateutil==2.8.2
    - pytorch-ignite==0.4.10
    - pytz==2022.7
    - pyyaml==6.0
    - pyyaml-env-tag==0.1
    - regex==2023.5.5
    - ruamel-yaml==0.17.21
    - ruamel-yaml-clib==0.2.7
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - spglib==2.0.2
    - sqlalchemy==1.4.45
    - stevedore==3.5.2
    - sympy==1.10.1
    - tabulate==0.9.0
    - tenacity==8.1.0
    - threadpoolctl==3.1.0
    - toolz==0.12.0
    - torch-cluster==1.6.0+pt112cu116
    - torch-geometric==2.2.0
    - torch-scatter==2.1.0+pt112cu116
    - torch-sparse==0.6.16+pt112cu116
    - torch-spline-conv==1.2.1+pt112cu116
    - tqdm==4.64.1
    - uncertainties==3.1.7
    - watchdog==3.0.0
    - wcwidth==0.2.5
    - xmltodict==0.13.0
    - zipp==3.11.0