task_name: homo_lumo
target_index: 5
finetune_type: geometry # null (train from scratch), property, geometry
conformer: mix_GT_relax # GT, rdkit, relaxation, DFT_1st, mix_GT_relax
return_vec: true
position_weight: 0.1 # default: 0.1
noise_std: 0.3 # default: 0.02
add_noise_to_relax: false


# Global variables
name: subset_PaiNN_geometry_finetune
dataset_name: Molecule3D
max_steps: 2000000
job_type: train
pretrained_foundation: null # name of pretrained split or 'null'
pretrained_downstream: <pretrained downstream PaiNN model>
ckpt_path: null # path to checkpoint for training resume or test run

# Datamodule parameters
root: ./
batch_size: 256
num_workers: 8
split_mode: random
processed_folder: processed_relax_subset_new
sample_relaxed_traj: true

# Devices
devices: [3]

# Trainer parameters
gradient_clip_algorithm: null
gradient_clip_val: null

# configs
defaults:
  - _self_
  - datamodule: pyg.yaml  # dataset config
  - model: painn_auxiliary.yaml  # painn_auxiliary.yaml  # model config
  - callbacks: default.yaml  # pl callbacks config
  - loggers: wandb.yaml  # pl loggers config
  - trainer: train.yaml  # trainer config

# need this to set working dir as current dir
hydra:
  output_subdir: null
  run:
    dir: .
original_work_dir: ${hydra:runtime.cwd}

seed: 42