name: LatentDiff
channels:
  - bioconda
  - pytorch
  - plotly
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - absl-py=1.1.0=pyhd8ed1ab_0
  - aiohttp=3.8.1=py310h7f8727e_1
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - anyio=3.6.1=py310hff52083_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py310h5764c6d_2
  - asttokens=2.0.5=pyhd8ed1ab_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-timeout=4.0.1=pyhd3eb1b0_0
  - atk-1.0=2.36.0=h3371d22_4
  - attrs=21.4.0=pyhd3eb1b0_0
  - babel=2.10.3=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - biopython=1.79=py310h5764c6d_2
  - biotite=0.34.1=py310hde88566_1
  - blas=1.0=mkl
  - bleach=5.0.1=pyhd8ed1ab_0
  - blessings=1.7=py310h06a4308_1002
  - blinker=1.4=py310h06a4308_0
  - blosc=1.21.1=h83bc5f7_3
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - brotlipy=0.7.0=py310h7f8727e_1002
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2023.5.7=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=4.2.2=pyhd3eb1b0_0
  - cairo=1.16.0=ha61ee94_1011
  - certifi=2023.5.7=pyhd8ed1ab_0
  - cffi=1.15.0=py310hd667e15_1
  - cftime=1.6.1=py310hde88566_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py310h06a4308_0
  - colorama=0.4.5=pyhd8ed1ab_0
  - cryptography=37.0.1=py310h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - curl=7.82.0=h7f8727e_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - debugpy=1.6.0=py310hd8f1fbe_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=py_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=0.8.3=pyhd8ed1ab_0
  - expat=2.4.8=h27087fc_0
  - fasteners=0.17.3=pyhd8ed1ab_0
  - ffmpeg=4.2.2=h20bf706_0
  - fftw=3.3.10=nompi_h77c792f_102
  - flit-core=3.7.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.0=h8e229c2_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.33.3=py310h5764c6d_0
  - freetype=2.11.0=h70c0345_0
  - fribidi=1.0.10=h36c2ea0_0
  - frozenlist=1.2.0=py310h7f8727e_1
  - gdk-pixbuf=2.42.8=hff1cb4f_0
  - gettext=0.19.8.1=h73d1719_1008
  - ghostscript=9.54.0=h27087fc_2
  - giflib=5.2.1=h7b6447c_0
  - gitdb=4.0.9=pyhd8ed1ab_0
  - gitpython=3.1.27=pyhd8ed1ab_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - google-auth=2.6.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.4=pyhd3eb1b0_0
  - gpustat=0.6.0=pyhd8ed1ab_1
  - gputil=1.4.0=pyh9f0ad1d_0
  - graphite2=1.3.13=h58526e2_1001
  - graphviz=5.0.0=h5abf519_0
  - griddataformats=1.0.1=pyhd8ed1ab_0
  - grpcio=1.42.0=py310hce63b2e_0
  - gsd=2.5.3=py310hde88566_0
  - gtk2=2.24.33=h90689f9_2
  - gts=0.7.6=h64030ff_2
  - h5py=3.7.0=nompi_py310h06dffec_100
  - harfbuzz=4.4.1=hf9f4e7c_0
  - hdf4=4.2.15=h10796ff_3
  - hdf5=1.12.1=nompi_h2750804_100
  - icu=70.1=h27087fc_0
  - idna=3.3=pyhd3eb1b0_0
  - imageio=2.22.0=pyhfa7a67d_0
  - imagemagick=7.1.0.43=pl5321h2098167_0
  - importlib-metadata=4.11.3=py310h06a4308_0
  - importlib_resources=5.8.0=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.9.1=py310h06a4308_0
  - ipython=8.4.0=py310hff52083_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.7.1=pyhd8ed1ab_0
  - jbig=2.1=h7f98852_2003
  - jedi=0.18.1=py310hff52083_1
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9e=h7f8727e_0
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=4.6.1=pyhd8ed1ab_0
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=4.10.0=py310hff52083_0
  - jupyter_server=1.18.1=pyhd8ed1ab_0
  - jupyterlab=3.4.3=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.12.0=py310h06a4308_0
  - jupyterlab_widgets=1.1.1=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.3=py310hbf28c38_0
  - krb5=1.19.3=h3790be6_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h9c3ff4c_0
  - libblas=3.9.0=12_linux64_mkl
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcblas=3.9.0=12_linux64_mkl
  - libcurl=7.82.0=h0b77cf5_0
  - libdeflate=1.12=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgd=2.3.3=h18fbbfe_3
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libglib=2.70.2=h174f98d_4
  - libgomp=12.1.0=h8d9b700_16
  - libiconv=1.16=h516909a_0
  - libidn2=2.3.2=h7f8727e_0
  - liblapack=3.9.0=12_linux64_mkl
  - libnetcdf=4.8.1=nompi_hb3fd0d9_101
  - libnghttp2=1.46.0=hce63b2e_0
  - libnsl=2.0.0=h7f98852_0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.20.1=h4ff587b_0
  - librsvg=2.54.4=h7abd40a_0
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.4.0=hc85c160_1
  - libtool=2.4.6=h9c3ff4c_1008
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.40.0=h7b6447c_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.9.14=h22db469_3
  - libzip=1.8.0=h5cef20c_0
  - libzlib=1.2.12=h166bdaf_1
  - lz4-c=1.9.3=h295c915_1
  - lzo=2.10=h516909a_1000
  - markdown=3.3.4=py310h06a4308_0
  - markupsafe=2.1.1=py310h5764c6d_1
  - matplotlib-base=3.5.2=py310h5701ce4_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mdanalysis=2.2.0=py310h769672d_0
  - mdtraj=1.9.7=py310hd8d60c7_1
  - mistune=0.8.4=py310h6acc77f_1005
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py310h7f8727e_0
  - mkl_fft=1.3.1=py310hd6ae3a3_0
  - mkl_random=1.2.2=py310h00e6091_0
  - mmtf-python=1.1.2=py_0
  - mrcfile=1.3.0=pyh44b312d_0
  - msgpack-python=1.0.4=py310hbf28c38_0
  - multidict=5.1.0=py310h7f8727e_2
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclassic=0.4.3=pyhd8ed1ab_0
  - nbclient=0.6.6=pyhd8ed1ab_0
  - nbconvert=6.5.0=pyhd8ed1ab_0
  - nbconvert-core=6.5.0=pyhd8ed1ab_0
  - nbconvert-pandoc=6.5.0=pyhd8ed1ab_0
  - nbformat=5.4.0=pyhd8ed1ab_0
  - ncurses=6.3=h7f8727e_2
  - nest-asyncio=1.5.5=pyhd8ed1ab_0
  - netcdf4=1.6.0=nompi_py310h947f774_100
  - nettle=3.7.3=hbbd107a_1
  - nglview=3.0.3=pyh8a188c0_0
  - notebook=6.4.12=pyha770c72_0
  - notebook-shim=0.1.0=pyhd8ed1ab_0
  - numexpr=2.8.3=py310hcea2de6_0
  - numpy=1.22.3=py310hfa59a62_0
  - numpy-base=1.22.3=py310h9585f30_0
  - nvidia-ml=7.352.0=pyhd3eb1b0_0
  - oauthlib=3.1.0=py_0
  - ocl-icd=2.3.1=h7f98852_0
  - ocl-icd-system=1.0.0=1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=hb52868f_1
  - openmm=7.7.0=py310hccf1d78_1
  - openssl=1.1.1u=hd590300_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandoc=2.18=ha770c72_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.50.8=hbd2fdc8_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pathtools=0.1.2=py_1
  - patsy=0.5.2=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - perl=5.32.1=2_h7f98852_perl5
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.0.1=py310h22f2fdc_0
  - pip=21.2.4=py310h06a4308_0
  - pixman=0.40.0=h36c2ea0_0
  - pkg-config=0.29.2=h36c2ea0_1008
  - plotly=5.9.0=py_0
  - prometheus_client=0.14.1=pyhd8ed1ab_0
  - promise=2.3=py310hff52083_6
  - prompt-toolkit=3.0.30=pyha770c72_0
  - psutil=5.9.0=py310h5eee18b_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.12.0=pyhd8ed1ab_0
  - pyjwt=2.4.0=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyrsistent=0.18.1=py310h5764c6d_1
  - pysocks=1.7.1=py310h06a4308_0
  - pytables=3.7.0=py310hf5df6ce_0
  - python=3.10.5=h582c2e5_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.15.3=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytorch=1.11.0=py3.10_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - pytz=2022.1=pyhd8ed1ab_0
  - pyyaml=6.0=py310h5764c6d_4
  - pyzmq=23.2.0=py310h330234f_0
  - readline=8.1.2=h7f8727e_1
  - requests=2.28.0=py310h06a4308_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scikit-learn=1.1.1=py310hffb9edd_0
  - scipy=1.8.1=py310h7612f91_0
  - seaborn=0.11.2=hd8ed1ab_0
  - seaborn-base=0.11.2=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - sentry-sdk=1.9.10=pyhd8ed1ab_0
  - setproctitle=1.3.2=py310h5764c6d_0
  - setuptools=61.2.0=py310h06a4308_0
  - shortuuid=1.0.9=pyha770c72_1
  - six=1.16.0=pyhd3eb1b0_1
  - smmap=3.0.5=pyh44b312d_0
  - snappy=1.1.9=hbd366e4_1
  - sniffio=1.2.0=py310hff52083_3
  - soupsieve=2.3.1=pyhd8ed1ab_0
  - sqlite=3.38.5=hc218d9a_0
  - stack_data=0.3.0=pyhd8ed1ab_0
  - statsmodels=0.13.2=py310hde88566_0
  - tenacity=8.0.1=py310h06a4308_0
  - tensorboard=2.9.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.0=py310hca6d32c_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - terminado=0.15.0=py310hff52083_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tidynamics=1.0.0=py_0
  - tinycss2=1.1.1=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - tmalign=20170708=h1107714_4
  - tmux=3.3=h385fc29_0
  - torchaudio=0.11.0=py310_cu113
  - torchvision=0.12.0=py310_cu113
  - tornado=6.2=py310h5764c6d_0
  - tqdm=4.64.0=pyhd8ed1ab_0
  - traitlets=5.3.0=pyhd8ed1ab_0
  - tree=2.1.1=hd590300_0
  - typing-extensions=4.1.1=hd3eb1b0_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - tzdata=2022a=hda174b7_0
  - unicodedata2=14.0.0=py310h5764c6d_1
  - urllib3=1.26.9=py310h06a4308_0
  - wandb=0.13.1=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=1.3.3=pyhd8ed1ab_0
  - werkzeug=2.0.3=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=3.6.1=pyha770c72_0
  - x264=1!157.20191217=h7b6447c_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-libxt=1.2.1=h7f98852_2
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h7f8727e_1
  - yaml=0.2.5=h7f98852_2
  - yarl=1.6.3=py310h7f8727e_1
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.8.0=py310h06a4308_0
  - zlib=1.2.12=h166bdaf_1
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - contextlib2==21.6.0
    - dgl==1.1.1
    - dm-tree==0.1.6
    - e3nn==0.5.0
    - flatbuffers==1.12
    - gast==0.4.0
    - google-pasta==0.2.0
    - googledrivedownloader==0.4
    - isodate==0.6.1
    - jax==0.4.13
    - jaxlib==0.4.13+cuda11.cudnn86
    - keras==2.9.0
    - keras-preprocessing==1.1.2
    - libclang==14.0.1
    - ml-collections==0.1.1
    - ml-dtypes==0.2.0
    - mpmath==1.2.1
    - networkx==2.8.3
    - opt-einsum==3.3.0
    - opt-einsum-fx==0.1.4
    - pandas==1.4.2
    - protobuf==3.19.4
    - python-louvain==0.16
    - rdflib==6.1.1
    - sympy==1.11.1
    - tensorflow==2.9.1
    - tensorflow-estimator==2.9.0
    - tensorflow-io-gcs-filesystem==0.26.0
    - termcolor==1.1.0
    - torch-cluster==1.6.0
    - torch-geometric==2.1.0.post1
    - torch-scatter==2.0.9
    - torch-sparse==0.6.13
    - wget==3.2
    - wrapt==1.14.1
    - yacs==0.1.8
